# Generated by Django 5.1.7 on 2025-03-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meja',
            fields=[
                ('id_meja', models.AutoField(primary_key=True, serialize=False)),
                ('no_meja', models.CharField(max_length=100, unique=True)),
                ('kapasitas', models.IntegerField()),
            ],
            options={
                'db_table': 'meja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_menu', models.AutoField(primary_key=True, serialize=False)),
                ('nama_menu', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MenuKategori',
            fields=[
                ('id_kategori', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'menu_kategori',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservasi',
            fields=[
                ('id_reservasi', models.AutoField(primary_key=True, serialize=False)),
                ('nama_customer', models.CharField(max_length=100)),
                ('tanggal_reservasi', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'reservasi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('id_stok', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah_stok', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stok',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id_transaksi', models.AutoField(primary_key=True, serialize=False)),
                ('total_harga', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('ppn', models.DecimalField(decimal_places=0, max_digits=10)),
                ('diskon', models.DecimalField(decimal_places=0, max_digits=10)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('status_pembayaran', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'transaksi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransaksiDetail',
            fields=[
                ('id_detail', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah', models.IntegerField(blank=True, null=True)),
                ('sub_total', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'transaksi_detail',
                'managed': False,
            },
        ),
    ]
