# Generated by Django 5.1.7 on 2025-03-17 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoran_app', '0002_alter_reservasi_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservasi',
            options={'managed': False},
        ),
    ]
